CPU=RISCV

PREFIX = riscv32-unknown-elf

##
## Tools we use for building
##
CC	    = $(PREFIX)-gcc
LD	    = $(PREFIX)-gcc
ASM     = $(PREFIX)-as
OBJCOPY	= $(PREFIX)-objcopy
OBJDUMP	= $(PREFIX)-objdump
AR     	= $(PREFIX)-ar
GDB	    = $(PREFIX)-gdb
FLASH	= $(shell which st-flash)
MKDIR   = mkdir
RM      = rm

##
## Project Directories
##
SRC_DIR  = src
OBJ_DIR  = objects
INC_DIR  = includes
EXEC_DIR = executable
LIB_DIR = library
DEP_DIR  = dep
LD_DIR   = linker
